FROM alpine:3.18.5
RUN apk add git
RUN apk add make
RUN apk add g++

RUN git clone https://github.com/adarsh-kishore786/Projects.git 
RUN cd Projects/CGPA

WORKDIR Projects/CGPA

CMD echo "Hello, World!"
